name: super_app
description: "Supper App For Multiple Clients"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

# run this "flutter pub run flutter_launcher_icons"
flutter_icons:
  # android: "ic_launcher"
  ios: true
  image_path: "asset/image/appa.png" 

flutter:

  uses-material-design: true

  assets:
    - asset/theme/theme_appa.json
    - asset/theme/theme_appb.json

    - asset/image
